### ISSUE TITLE
ValueError: empty vocabulary; perhaps the documents only contain stop words

### ISSUE THREAD

**Issue by MuhammadMohsan** [yassersouri/classify-text#1]
Dear sir, first of all thank you very much for your response. I have resolved the error of path, but now its giving error "ValueError: empty vocabulary; perhaps the documents only contain stop words".The screen shot of the error is being attached. And yes i'm using the Windows (OS). Is it necessary to use UNIX based system? Waiting for your responce. Thanks in advance.
![image](https://cloud.githubusercontent.com/assets/21970885/20749533/8724b73e-b714-11e6-8b41-e649fcbaa71b.png)
Regards,
M Mohsan

**Comment by yassersouri** [comment]
It seems that you are not giving it the correct path. "\dataset" is incorrect. Give it the absolute path to the exact location of the dataset.
