### ISSUE TITLE
BOW & TF

### ISSUE THREAD

**Issue by gocen** [yassersouri/classify-text#3]
What is the difference between BOW and TF?

**Comment by yassersouri** [comment]
BOW (bag of words): is each word present or not

TF (term frequency): how many times a word (or term) is present.

**Comment by gocen** [comment]
But this page doesn't describe like you
https://en.wikipedia.org/wiki/Bag-of-words_model

**Comment by yassersouri** [comment]
I think we should be looking at this: https://scikit-learn.org/stable/modules/feature_extraction.html#the-bag-of-words-representation

**Comment by gocen** [comment]
https://scikit-learn.org/stable/modules/feature_extraction.html#the-bag-of-words-representation
This page also says:
Documents are described by word occurrences

**Comment by yassersouri** [comment]
You might be right, It has been such a long time since I have written this code I might have forgotten.

Specifically this is what I use for BOW without any arguments:
https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html
